### ISSUE TITLE
Pinecone from Documents does not work on Lambda because multprocessing

### ISSUE THREAD

**Issue by ryaneggz** [promptengineers-ai/core#28]
https://github.com/langchain-ai/langchain/issues/11168

https://chat.openai.com/share/6a74f21b-a418-4206-8aa0-5c149c5ddc26

```bash
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 22, in lambda_handler
    result = pinecone_service.from_documents(
  File "/var/task/promptengineers/services/pinecone.py", line 106, in from_documents
    return Pinecone.from_documents(
  File "/var/task/langchain_core/vectorstores.py", line 510, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/var/task/langchain/vectorstores/pinecone.py", line 421, in from_texts
    pinecone.add_texts(
  File "/var/task/langchain/vectorstores/pinecone.py", line 138, in add_texts
    async_res = [
  File "/var/task/langchain/vectorstores/pinecone.py", line 139, in <listcomp>
    self._index.upsert(
  File "/var/task/pinecone/core/utils/error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
  File "/var/task/pinecone/index.py", line 150, in upsert
    return self._upsert_batch(vectors, namespace, _check_type, **kwargs)
  File "/var/task/pinecone/index.py", line 237, in _upsert_batch
    return self._vector_api.upsert(
  File "/var/task/pinecone/core/client/api_client.py", line 776, in __call__
    return self.callable(self, *args, **kwargs)
  File "/var/task/pinecone/core/client/api/vector_operations_api.py", line 956, in __upsert
    return self.call_with_http_info(**kwargs)
  File "/var/task/pinecone/core/client/api_client.py", line 838, in call_with_http_info
    return self.api_client.call_api(
  File "/var/task/pinecone/core/client/api_client.py", line 421, in call_api
    return self.pool.apply_async(self.__call_api, (resource_path,
  File "/var/task/pinecone/core/client/api_client.py", line 107, in pool
    self._pool = ThreadPool(self.pool_threads)
  File "/var/lang/lib/python3.11/multiprocessing/pool.py", line 930, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/var/lang/lib/python3.11/multiprocessing/pool.py", line 196, in __init__
    self._change_notifier = self._ctx.SimpleQueue()
  File "/var/lang/lib/python3.11/multiprocessing/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/var/lang/lib/python3.11/multiprocessing/queues.py", line 341, in __init__
    self._rlock = ctx.Lock()
  File "/var/lang/lib/python3.11/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/var/lang/lib/python3.11/multiprocessing/synchronize.py", line 169, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/var/lang/lib/python3.11/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(END RequestId: 7cb38183-cf35-4d05-9cbf-5758e4d3ee6c
REPORT RequestId: 7cb38183-cf35-4d05-9cbf-5758e4d3ee6c	Duration: 1783.23 ms	Billed Duration: 1784 ms	Memory Size: 3072 MB	Max Memory Used: 293 MB	Init Duration: 5258.48 ms	
```

**Comment by ryaneggz** [comment]
Solved here but needs to be brought under this repo organzation.
https://github.com/ryaneggz/lambda-python-starter/tree/lambda-loader
